name: Java CI with Maven

on:
  push:
    branches:
    - main
    tags:
    - v[0-9]+.[0-9]+.[0-9]+**
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11

    - name: Cache Local Maven Repo
      uses: actions/cache@v2.1.2
      with:
        path: |
          ~/.m2/repository
        key: maven-repo

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1

    - name: Build with Maven
      run: mvn -B verify
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USENAME: ${{ github.actor }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11

    - name: Cache Local Maven Repo
      uses: actions/cache@v2.1.2
      with:
        path: |
          ~/.m2/repository
        key: maven-repo

    - name: Build with Maven
      run: mvn -B package -DskipTests

    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push BPE image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/samply/blaze:${{ github.sha }}
